platform :ios, '7.0'
pod 'SocketRocket'
pod 'JSONKit-NoWarning'
pod 'KVOController'
#pod 'Reveal-iOS-SDK'
pod 'TTTAttributedLabel'
pod 'CAAnimation-EasingEquations'
pod 'JASidePanels'
pod 'FlurrySDK'
